### ISSUE TITLE
將shopping cart的內容存入資料庫

### ISSUE THREAD

**Issue by Vghxv** [CSIEHaTerX/Backend#103]
新增tranaction status的狀態 (Ordering)及所需的api
使guest將東西加入購物車後再創建帳號
商品不會無情的跟著cookie一起被刪掉

**Comment by Dragonfly911117** [comment]
我不覺得在沒有帳號的情況下加入購物車是正常的行為

**Comment by cuchaos** [comment]
但當時是參考原價屋可以以顧客身分將商品加入購物車，我認為只要確認最後結帳時一定要登入就行

**Comment by Vghxv** [comment]
true

**Comment by Dragonfly911117** [comment]
cookie aint backend-thing, closing it
