### ISSUE TITLE
 Model CreateAccountForm doesn't match our DB schema's order

### ISSUE THREAD

**Issue by Dragonfly911117** [CSIEHaTerX/Backend#35]
![image](https://github.com/NTUT-Furniture/Backend/assets/55215882/ad194c02-e2be-4715-90ef-f714610074e5)

**Comment by Dragonfly911117** [comment]
The null-able constraint of email is fucked as well.

**Comment by kyynk** [comment]
我目前有在Login的PR修掉

**Comment by kyynk** [comment]
還是我先用一個新的branch去修?

**Comment by Dragonfly911117** [comment]
> 還是我先用一個新的branch去修?

LGTM
