### ISSUE TITLE
JSONResponse section are too complex

### ISSUE THREAD

**Issue by kryr34** [CSIEHaTerX/Backend#40]
I've noticed repetitive `JSONResponse` with complex nesting and similar structures. like
https://github.com/NTUT-Furniture/Backend/blob/602988d96d8b50c1a8589c0daddd279aae82112d/router/shop.py#L34-L50

I suggest using helper functions to enhance code readability.
<details>
<summary>Ex.</summary>

```py
def my_success_response(result=''):
  return  JSONResponse(
    status_code=status.HTTP_200_OK,
    content=jsonable_encoder(
      {
        "msg": "Success",
        "data": result
      }
    )
  )

# usage
def get_money():
  ...
  return my_success_response(result=money)
```
</details>

## Update

I'm not familiar with FastAPI, but it seems that you could handle the response using a model following [this tutorial](https://fastapi.tiangolo.com/tutorial/response-model/).

p.s. imo the field `msg` is not necessary unless there's failure reason. http status can replace it.

**Comment by Vghxv** [comment]
> p.s. imo the field msg is not necessary unless there's failure reason. http status can replace it.

i think user should at least know what actually happened rather than just http status
or mabye that's frontend's job?
ps. helper function is a good idea
