### ISSUE TITLE
Account, Product, Shop should be in enabled(or disabled) state.

### ISSUE THREAD

**Issue by pudding483** [CSIEHaTerX/Backend#42]
In order not to delete the Account, Product, Shop directly, we should put on "state" making Account, Product, Shop looks like being deleted.

**Comment by Dragonfly911117** [comment]
帳號需要多一個權限的欄位，以區別一般跟超級帳號

**Comment by Dragonfly911117** [comment]
> 帳號需要多一個權限的欄位，以區別一般跟超級帳號

或是再開一個超級帳號的表 idk

**Comment by Dragonfly911117** [comment]
#49
