### ISSUE TITLE
Do things to update_time from Account, Shop, Product, etc

### ISSUE THREAD

**Issue by Dragonfly911117** [CSIEHaTerX/Backend#60]

**Comment by Vghxv** [comment]
are they not updated when updated?

**Comment by Dragonfly911117** [comment]
![image](https://github.com/NTUT-Furniture/Backend/assets/55215882/0ee48bd1-81a3-4aff-9082-2a3e4780d4d4)
they do?

**Comment by Vghxv** [comment]
they don't?

**Comment by Dragonfly911117** [comment]
![image](https://github.com/NTUT-Furniture/Backend/assets/55215882/4a489388-3e5c-4aa5-a5c7-7dfca86f7b91)
![image](https://github.com/NTUT-Furniture/Backend/assets/55215882/ce5f716a-8e34-43fa-8c02-47160772bc14)

Sadly, threy don't.

**Comment by Vghxv** [comment]
Sol lies here I think
https://dev.mysql.com/doc/refman/8.0/en/show-columns.html

> @Extra
> Any additional information that is available about a given column. The value is nonempty in these cases:
> auto_increment for columns that have the AUTO_INCREMENT attribute.
> on update CURRENT_TIMESTAMP for TIMESTAMP or DATETIME columns that have the ON UPDATE CURRENT_TIMESTAMP attribute.
> VIRTUAL GENERATED or STORED GENERATED for generated columns.
> DEFAULT_GENERATED for columns that have an expression default value

**Comment by Vghxv** [comment]
note: by adding default_generated, pass value to the column produce error.
