### ISSUE TITLE
I want Update Account but "Permission denied".

### ISSUE THREAD

**Issue by cuchaos** [CSIEHaTerX/Backend#68]
![image](https://github.com/NTUT-Furniture/Backend/assets/122445324/1965ffb8-91bc-4b9b-9434-fb1e3150c109)

**Comment by Dragonfly911117** [comment]
Provide loggined account's role and the request form you sent.

**Comment by cuchaos** [comment]
![image](https://github.com/NTUT-Furniture/Backend/assets/122445324/626248ab-5156-44b7-b0ad-fc6de9ad12ed)

**Comment by cuchaos** [comment]
登入帳號是我自己建立的
e-mail:asd@asd.asd
pwd:asd

**Comment by Dragonfly911117** [comment]
> Provide loggined account's role and the request form you sent.

If you're updating your own account, there's no need to provide account_uuid; this parameter is for admins to update other accounts.

**Comment by cuchaos** [comment]
可以了

**Comment by cuchaos** [comment]
我關issue

**Comment by Dragonfly911117** [comment]
> 登入帳號是我自己建立的 e-mail:[asd@asd.asd](mailto:asd@asd.asd) pwd:asd

Accounts created through the backend API won't have admin privileges. To update their roles, you'll need to perform database operations or use an admin account to modify their account information.
