### ISSUE TITLE
Create different accounts success but the return value of token are the same

### ISSUE THREAD

**Issue by cuchaos** [CSIEHaTerX/Backend#79]
![image](https://github.com/NTUT-Furniture/Backend/assets/122445324/dd1f1e77-254f-4843-b99b-b77c93ee1ddf)
![image](https://github.com/NTUT-Furniture/Backend/assets/122445324/f8f5326e-b7c4-41fe-841e-d002bb554745)

**Comment by Vghxv** [comment]
bro token are not the same ~~are u blind~~

**Comment by cuchaos** [comment]
ok my bad
