### ISSUE TITLE
HateList table needed

### ISSUE THREAD

**Issue by Dragonfly911117** [CSIEHaTerX/Backend#83]
As discussed on Discord, the current comment schema doesn't keep track of which account has already liked or disliked a comment. This allows users to repeatedly like or dislike a comment by clicking the button multiple times.

Following(or something like this) changes must be made:
```diff
create table Comment
(
+   comment_uuid     varchar(64)                         not null,
    transaction_uuid varchar(64)                         not null,
    account_uuid     varchar(64)                         not null,
    text             varchar(512)                        not null,
-    likes            int                                 not null,
-   dislikes        int                                 not null,
.
.
.
```
and
```sql
create table HateList
(
    hater_uuid   varchar(64)           not null,
    comment_uuid varchar(64)           not null,
    if_hates     tinyint(1)            not null # 0 for liking this comment; 1 for disliking.
);
```

**Comment by Vghxv** [comment]
if_hates should have thrid state, not like or dislike

**Comment by Dragonfly911117** [comment]
like, dislike, and?

**Comment by Vghxv** [comment]
not react to that comment

**Comment by Dragonfly911117** [comment]
> not react to that comment

wdym? There's no way to react to a comment without liking/disliking it.

**Comment by Vghxv** [comment]
oh, get it

**Comment by Dragonfly911117** [comment]
The Frontend Team can easily identify that the current user hasn't reacted to a comment by checking the HateList API with the account_uuid and comment_uuid; if they receive a 404 error, it means there's no existing reaction from that user towards that comment.
