### ISSUE TITLE
Update Coupon schema

### ISSUE THREAD

**Issue by Dragonfly911117** [CSIEHaTerX/Backend#84]
## Add
- `coupon_uuid` as pk
- `is_active`: check if the coupon is valid on used
- auto-deactive-function

## Remove
- `coupon_code` to be a not null attribute 
- auto-delete-function: it fucks pricing things in transactions up after deleting the coupon

**Comment by Vghxv** [comment]
@Dragonfly911117  coupon is gone@@

**Comment by Dragonfly911117** [comment]
> @Dragonfly911117  coupon is gone@@

What

**Comment by Dragonfly911117** [comment]
wdym gone?
![image](https://github.com/NTUT-Furniture/Backend/assets/55215882/0b93a450-61ec-4a06-98a0-b53a01fa2310)

**Comment by Dragonfly911117** [comment]
I see. u mean coupons in db
![image](https://github.com/NTUT-Furniture/Backend/assets/55215882/b562c736-8ff0-48a2-83e4-56dba72eb03c)

**Comment by Vghxv** [comment]
close as merged in #89
