### ISSUE TITLE
jwt token validation

### ISSUE THREAD

**Issue by Vghxv** [CSIEHaTerX/Backend#9]
after user login, a token is provided for user to access resources

**Comment by Dragonfly911117** [comment]
will do it after #28

**Comment by Vghxv** [comment]
skipped

**Comment by Dragonfly911117** [comment]
I mean skip the [chapter](https://fastapi.tiangolo.com/tutorial/security/#in-a-hurry)'s detail and advanced auth not the whole jwt part
